In [10]:
# bt1

a = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

for i in a:
    if i % 2 == 0:
        print(i, " ")


b = tuple(a)
print(b)

c = dict()
for i in range(len(a)):
    c[i] = a[i]
print(c)

d = set(a)
print(d)

print(len(a) - len(d))

2  
2  
4  
(1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
{0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
{1, 2, 3, 4, 5, 7, 9}
3


In [15]:
# bt2
import json

f = open("data.txt", "r")
print(f.read())

student = dict({
  "name": "An",
  "age": 20,
  "scores": [8, 9, 7]
})

with open("student.json", "w") as f:
  json.dump(student, f)

abcd
alcx
ácca
adad
accss


In [19]:
# bt3
import numpy as np

arr = np.arange(12).reshape(3, 4)

print(arr[1])
print(arr[:, 2])
print(arr[0:2, 1:3])

arr_float = arr.astype(np.float64)
print(arr_float.dtype)



[4 5 6 7]
[ 2  6 10]
[[1 2]
 [5 6]]
float64


In [ ]:
# bt4
import pandas as pd

name = ['An','Bình','Châu','Dũng','Hà']
age = [20,21,22,20,23]
score = [7.5, 8.0, 6.5, 9.0, 8.5] 

df = pd.DataFrame({'name': name,'age': age,'score': score})

df.info()

df.describe()

df.loc[df['score'] > 8]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000

In [23]:
# bt5
import pandas as pd

students = pd.read_csv('students.csv')
scores = pd.read_csv('scores.csv')



merged = pd.merge(students, scores, on='id')

merged['min_score'] = merged['score']
merged['max_score'] = merged['score']
merged['mean_score'] = merged['score']



merged.to_csv('report.csv', index=False)




In [24]:
# bt6
import numpy as np

a = np.array([[1], [2], [3], [4]])
b = np.array([[10, 20, 30, 40, 50]])

print(a * b)

print(np.sqrt(a * b))

print(np.log(a * b))


[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
[[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
[[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]


In [27]:
# bt7
import pandas as pd
import numpy as np

data = {
    'name': ['An', 'Bình', 'Châu', 'Dũng'],
    'age': [20, np.nan, 22, 21],
    'score': [8.5, np.nan, 7.0, 9.0],
    'city': ['Hà Nội', 'HCM', np.nan, 'Hà Nội']
}

df = pd.DataFrame(data)

print(df.isna())

df['age'] = df['age'].fillna(df['age'].mean())
df['score'] = df['score'].fillna(df['score'].median())
df['city'] = df['city'].fillna("Unknown")

df['city'] = df['city'].astype('category')
print(df['city'].dtype)

def classify_score(score):
    if score >= 8.5:
        return 'Good'
    elif score >= 7.0:
        return 'Average'
    else:
        return 'Bad'

df['score_level'] = df['score'].apply(classify_score)
print(df[['name', 'score', 'score_level']])

age_mean = df['age'].mean()
age_std = df['age'].std()

df['age_normalized'] = (df['age'] - age_mean) / age_std

print(df)

    name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False
category
   name  score score_level
0    An    8.5        Good
1  Bình    8.5        Good
2  Châu    7.0     Average
3  Dũng    9.0        Good
   name   age  score     city score_level  age_normalized
0    An  20.0    8.5   Hà Nội        Good       -1.224745
1  Bình  21.0    8.5      HCM        Good        0.000000
2  Châu  22.0    7.0  Unknown     Average        1.224745
3  Dũng  21.0    9.0   Hà Nội        Good        0.000000


In [ ]:
# bt8
import pandas as pd
import json
from pathlib import Path
from datetime import datetime

logs_dir = Path('logs')


json_files = list(logs_dir.glob('*.json'))
for file in json_files:
    print(f"   - {file}")
print()


file_dates = {}
for file in json_files:
    date_str = file.stem.replace('log_', '')
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    file_dates[file.name] = date_obj
    print(f"   {file.name} -> {date_obj.strftime('%Y-%m-%d (%A)')}")
print()

all_data = []
for file in json_files:
    with open(file, 'r') as f:
        data = json.load(f)
        date_str = file.stem.replace('log_', '')
        for record in data:
            record['date'] = date_str
        all_data.extend(data)

df = pd.DataFrame(all_data)
print(df)
print()

daily_duration = df.groupby('date')['duration'].sum().reset_index()
daily_duration.columns = ['date', 'total_duration']
print(daily_duration)
print()

output_file = 'daily_report.csv'
daily_duration.to_csv(output_file, index=False)
print()

   - logs\log_2025-01-01.json
   - logs\log_2025-01-02.json
   - logs\log_2025-01-03.json

   log_2025-01-01.json -> 2025-01-01 (Wednesday)
   log_2025-01-02.json -> 2025-01-02 (Thursday)
   log_2025-01-03.json -> 2025-01-03 (Friday)

  user    action  duration        date
0    A     login         5  2025-01-01
1    B    logout         2  2025-01-01
2    A    upload        10  2025-01-01
3    C     login         3  2025-01-02
4    A  download         8  2025-01-02
5    B     login         4  2025-01-02
6    C    logout         1  2025-01-03
7    A     login         6  2025-01-03
8    B    upload        12  2025-01-03

         date  total_duration
0  2025-01-01              17
1  2025-01-02              15
2  2025-01-03              19


